name: Deploy to DigitalOcean

on:
  push:
    branches: [main]
  # Optional: Trigger when backend or frontend repos change
  repository_dispatch:
    types: [backend-updated, frontend-updated]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v3

      - name: Deploy to droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/purrvelous-deploy
            
            # Pull latest deployment configuration
            git pull origin main
            
            # Create .env file with secrets
            cat > .env << EOF
            JWT_SECRET="${{ secrets.JWT_SECRET }}"
            EOF
            
            # Pull latest submodules (frontend and backend repos)
            git submodule update --init --recursive
            git submodule update --remote
            
            # Stop existing containers
            docker-compose down
            
            # Rebuild and start containers
            docker-compose build --no-cache
            docker-compose up -d
            
            # Clean up old images
            docker image prune -f
            
            # Show container status
            docker-compose ps